### ISSUE TITLE
Polling Query Support

### ISSUE THREAD

**Issue by rmdwirizki** [reach-digital/polymer-apollo-client#1]
Hello, I'm rather new to graphql and now I'm trying to create a simple chat application with this package.. I don't see any item in todo list about reactivity, so do you have any suggestion about how to polling a graphql query with this package? or how to manually refetch all the information?

**Comment by paales** [comment]
Hi @rmdwirizki,

I haven't tested this personally, but there are two options:
1. Set the `pollInterval`: `<graphql-query poll-interval=4000></graphql-query>` https://www.webcomponents.org/element/reach-digital/polymer-apollo-client/elements/graphql-query#property-pollInterval
2. Call the `this.$.myQuery.execute()` method, it should refetch all the information. https://www.webcomponents.org/element/reach-digital/polymer-apollo-client/elements/graphql-query#method-execute

**Comment by rmdwirizki** [comment]
Thanks for the answer, but the `pollInterval` property doesn't work. And I already solved it by using `subscription` method with the help of another package https://github.com/aruntk/polymer-apollo#subscriptions
Well in fact, I prefer this library approach to write the query in a custom element though.

**Comment by FluorescentHallucinogen** [comment]
@rmdwirizki 
> And I already solved it by using subscription method with the help of another package https://github.com/aruntk/polymer-apollo#subscriptions
Well in fact, I prefer this library approach to write the query in a custom element though.

FYI, subscriptions support is implemented in #15. :wink:

**Comment by FluorescentHallucinogen** [comment]
@paales 
> Call the `this.$.myQuery.execute()` method, it should refetch all the information.

Just tested, it doesn't. Subsequent calls of `execute()` don't make network requests, return data from the cache and don't update the data in the cache.

`notifyOnNetworkStatusChange` property also doesn't work.

**Comment by FluorescentHallucinogen** [comment]
@rmdwirizki 
> but the `pollInterval` property doesn't work.

Just tested, `pollInterval` works like a charm.

@paales 
> Subsequent calls of `execute()` don't make network requests, return data from the cache and don't update the data in the cache.

I've solved this problem by setting the `fetchPolicy` property to `cache-and-network` value. Seems it’s by design.

`notifyOnNetworkStatusChange` property still for some reason doesn't work.
