### ISSUE TITLE
Bug: corrupted variables when using data binding

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [reach-digital/polymer-apollo-client#13]
If I pass static value (`"Test"`) to `variables` attribute, all is ok:

```html
<graphql-query variables='{"search": "Test"}' result="{{data}}">
  query myOperationName($search: String) {
    posts(where: {
      title_contains: $search
    }) {
      id
      title
      content
    }
  }
</graphql-query>
```

![static](https://user-images.githubusercontent.com/7892779/41811177-5fd722be-7713-11e8-8040-0d7ce07d1f19.png)

But If I pass dynamic value using data binding (`[[search]]`) to `variables` attribute, it produces corrupted variables:

```html
<paper-input
    label="Search"
    value="{{search}}">
</paper-input>

<graphql-query variables='{"search": "[[search]]"}' result="{{data}}">
  query myOperationName($search: String) {
    posts(where: {
      title_contains: $search
    }) {
      id
      title
      content
    }
  }
</graphql-query>
```

![dynamic](https://user-images.githubusercontent.com/7892779/41811196-be6bb9e8-7713-11e8-829d-0ccea3c843a4.png)

**Comment by FluorescentHallucinogen** [comment]
@paales Any ideas how to fix this?

**Comment by FluorescentHallucinogen** [comment]
When `variables='{"search": "Test"}'`:
```js
typeof this.variables //object
```

When `variables='{"search": "[[search]]"}'`:
```js
typeof this.variables //string
```

**Comment by paales** [comment]
```<graphql-query variables="[[computeVariables(search)]]" result="{{data}}">```

and then define the computeVariables method where you can just return a javascript object.

**Comment by FluorescentHallucinogen** [comment]
@paales Is it possible to change something in the code to make using data binding directly in `variables='{"search": "[[search]]"}'` possible without defining and using additional methods? It would be very useful.

**Comment by paales** [comment]
I'm not really sure how to actually implement it, searching in our own codebase and I always use the method:

```html
<graphql-query result="{{data}}" variables='[[_getVariables(quoteId)]]'>
  query GetQuote($id: ID!) {
    quote: quote(where: { id: $id }) {
      authorName
      authorTitle
      text
      asideTitle
      asideText
    }
  }
</graphql-query>
```

**Comment by FluorescentHallucinogen** [comment]
I've found solution! Just use `variables$='{"search": "[[search]]"}'` instead of `variables='{"search": "[[search]]"}'`. :wink:

Docs: https://www.polymer-project.org/2.0/docs/devguide/data-binding#anatomy-of-a-data-binding.

**Comment by paales** [comment]
Nice!
